# giving name of the pipeline
# clone the test
# install python 
# install dependencies
# run the code 
# test the code
name : "python_app"

on:
  push:
    branches:
      - main
jobs:
    fastapi:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
        - uses: actions/setup-python@v6
        - name: run the fastapi uvicorn
          run: uvicorn .:app --reload

    
